name: Raise curtain

on:
  repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: spotlight
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: SLACK_PERF_WEBHOOK=${{ secrets.SLACK_PERF_WEBHOOK }} npm run test